# Generated by Django 4.1.4 on 2023-07-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('emotional', models.CharField(choices=[('depr', 'Дипрессивные'), ('lov', 'Любовные'), ('happ', 'Счастливые')], max_length=255, verbose_name='Вид')),
                ('content', models.TextField(blank=True, verbose_name='Стих')),
            ],
            options={
                'verbose_name': 'Стих',
                'verbose_name_plural': 'Стихи',
            },
        ),
    ]
